// packages/dataviz-svelte/src/lib/AnimatedBubbleChart.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type AnimatedBubbleChartProps = {
    /** Dashboard store (provides rows + model). */
    store: DashboardStore;
    /** View id for the cross-filter graph. */
    viewId: string;
    /** Measure id mapped to x-axis. */
    x: string;
    /** Measure id mapped to y-axis. */
    y: string;
    /** Measure id whose value scales the bubble radius. */
    size: string;
    /** Dimension (or measure) whose distinct values define the time steps. */
    time: string;
    /** Optional dimension whose values drive categorical tones + labels. */
    series?: string;
    /** Accessible label for the chart. */
    label: string;
    width?: number;
    height?: number;
    class?: string;
  };
</script>

<script lang="ts">
  import { ScatterPlot as DsScatterPlot } from '@sentropic/design-system-svelte';
  import type { ScatterPlotDatum } from '@sentropic/design-system-svelte';
  import { distinctSorted, buildBubbleFrame } from '@sentropic/dataviz-core';
  import { useDashboard } from '../adapter.js';

  let {
    store,
    viewId,
    x,
    y,
    size,
    time,
    series,
    label,
    width,
    height,
    class: className,
  }: AnimatedBubbleChartProps = $props();

  // ── Dashboard reactivity ────────────────────────────────────────────────────
  const dash = $derived(useDashboard(store));

  // Derive sorted time steps from the full (cross-filtered) row set.
  const steps = $derived.by(() => {
    void $dash;
    const rows = store.applyCrossfilter(viewId);
    return distinctSorted(rows, time);
  });

  // ── Animation state ─────────────────────────────────────────────────────────
  let stepIndex = $state(0);
  let playing = $state(false);

  // Clamp index whenever `steps` changes (e.g. crossfilter removes a step).
  $effect(() => {
    if (stepIndex >= steps.length) stepIndex = Math.max(0, steps.length - 1);
  });

  // Timer: advance one step per second while playing.
  $effect(() => {
    if (!playing) return;
    const id = setInterval(() => {
      stepIndex = (stepIndex + 1) % Math.max(1, steps.length);
    }, 1000);
    return () => clearInterval(id);
  });

  function togglePlay() {
    playing = !playing;
  }

  function handleSlider(e: Event) {
    stepIndex = Number((e.target as HTMLInputElement).value);
    playing = false;
  }

  // ── Current frame ───────────────────────────────────────────────────────────
  const currentStep = $derived(steps[stepIndex] ?? '');

  const frame = $derived.by(() => {
    void $dash;
    const rows = store
      .applyCrossfilter(viewId)
      .filter((row) => String(row[time]) === currentStep);
    return buildBubbleFrame(store.model, rows, { x, y, size, series });
  });
</script>

<div
  class={['dataviz-animated-bubble', className].filter(Boolean).join(' ') || undefined}
  style="display:flex; flex-direction:column; gap:var(--st-spacing-3, 12px);"
>
  <!-- Chart area -->
  <DsScatterPlot
    data={frame.data as ScatterPlotDatum[]}
    xLabel={frame.xLabel}
    yLabel={frame.yLabel}
    {width}
    {height}
    {label}
  />

  <!-- Time-step controls -->
  <div
    role="group"
    aria-label="Contrôle temporel"
    style="display:flex; align-items:center; gap:var(--st-spacing-2, 8px); padding:0 var(--st-spacing-2, 8px);"
  >
    <button
      type="button"
      aria-label={playing ? 'Pause' : 'Lecture'}
      onclick={togglePlay}
      style="
        min-width: 2rem;
        aspect-ratio: 1;
        border: 1px solid var(--st-color-border, #ccc);
        border-radius: var(--st-radius-sm, 4px);
        background: var(--st-color-surface, #fff);
        color: var(--st-color-text, inherit);
        cursor: pointer;
        font-size: 1rem;
        display: flex;
        align-items: center;
        justify-content: center;
      "
    >
      {playing ? '⏸' : '▶'}
    </button>

    <input
      type="range"
      min={0}
      max={Math.max(0, steps.length - 1)}
      value={stepIndex}
      aria-label="Pas de temps"
      aria-valuetext={currentStep}
      oninput={handleSlider}
      style="flex:1; accent-color:var(--st-color-accent, currentColor);"
    />

    <span
      aria-live="polite"
      aria-atomic="true"
      style="
        min-width: 4ch;
        text-align: right;
        font-variant-numeric: tabular-nums;
        color: var(--st-color-text-muted, inherit);
        font-size: var(--st-font-size-sm, 0.875rem);
      "
    >
      {currentStep}
    </span>
  </div>
</div>

// packages/dataviz-angular/src/lib/AnimatedBubbleChart.ts
import { ChangeDetectionStrategy, Component, Input as NgInput, inject } from '@angular/core';
import type { OnChanges, OnDestroy, OnInit } from '@angular/core';
import { ChangeDetectorRef } from '@angular/core';
import { ScatterPlot as DsScatterPlot, type ScatterPlotDatum } from '@sentropic/design-system-angular';
import { buildBubbleFrame, distinctSorted, type DashboardStore } from '@sentropic/dataviz-core';
import { toSignalStore, type AngularSignalStore } from '../adapter.js';

export type AnimatedBubbleChartProps = {
  /** Dashboard store (provides rows + model). */
  store: DashboardStore;
  /** View id for the cross-filter graph. */
  viewId: string;
  /** Measure id mapped to x-axis. */
  x: string;
  /** Measure id mapped to y-axis. */
  y: string;
  /** Measure id whose value scales the bubble radius. */
  size: string;
  /** Dimension (or measure) whose distinct values define the time steps. */
  time: string;
  /** Optional dimension whose values drive categorical tones + labels. */
  series?: string;
  /** Accessible label for the chart. */
  label: string;
  width?: number;
  height?: number;
  class?: string;
};

/**
 * A bubble chart animated over sorted time steps, with native play/pause and
 * time-step controls beside the design-system ScatterPlot.
 *
 * tools/dataviz-angular-port refuses this shape: `setup()` holds local
 * animation state (`stepIndex`/`playing` refs) plus an interval timer and
 * renders several siblings (chart + control group), not one terminal `h()`
 * over a derived value (see tools/dataviz-angular-port/README.md). The
 * derivation itself is the shared core engine (`distinctSorted` /
 * `buildBubbleFrame`), reused never re-derived per PATTERN.md §3.
 *
 * The initial render is the comparable one: `playing` starts `false` and
 * `stepIndex` at `0`, so the first frame (timer started only by the play
 * button, cleared in `ngOnDestroy`) is exactly the SSR first frame the
 * parity harness compares against React.
 *
 * Layout follows the sources with native elements only — like Vue/React, the
 * controls are a plain button, range input and live region, not DS
 * components. The adapter-pattern guard forbids literal `style` attributes
 * in adapter sources, so the five Vue/React inline-style declarations have
 * no Angular counterpart; the parity run measures that residue instead of
 * hiding it.
 */
@Component({
  selector: 'st-dataviz-animated-bubble-chart',
  standalone: true,
  imports: [DsScatterPlot],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="rootClass">
      <st-scatter-plot
        [data]="data"
        [xLabel]="xLabel"
        [yLabel]="yLabel"
        [width]="width"
        [height]="height"
        [label]="label"
      ></st-scatter-plot>
      <div role="group" aria-label="Contrôle temporel">
        <button type="button" [attr.aria-label]="playing ? 'Pause' : 'Lecture'" (click)="togglePlay()">
          {{ playing ? '⏸' : '▶' }}
        </button>
        <input
          type="range"
          min="0"
          [max]="maxStep"
          [value]="safeIndex"
          aria-label="Pas de temps"
          [attr.aria-valuetext]="currentStep"
          (input)="handleSlider($event)"
        />
        <span aria-live="polite" aria-atomic="true">{{ currentStep }}</span>
      </div>
    </div>
  `,
})
export class AnimatedBubbleChart implements OnInit, OnChanges, OnDestroy {
  static readonly stComponentName = 'AnimatedBubbleChart';

  private readonly changeDetector = inject(ChangeDetectorRef);
  private signals?: AngularSignalStore;
  private unsubscribe: () => void = () => {};
  private timer: ReturnType<typeof setInterval> | undefined;

  @NgInput({ required: true }) set store(value: DashboardStore) {
    if (this.signals) this.signals.replace(value);
    else this.signals = toSignalStore(value);
    this.unsubscribe();
    this.unsubscribe = value.subscribe(() => {
      this.recompute();
      this.changeDetector.markForCheck();
    });
  }

  get store(): DashboardStore {
    if (!this.signals) {
      throw new Error('AnimatedBubbleChart: store is required.');
    }
    return this.signals.store;
  }

  @NgInput({ required: true }) viewId!: string;
  @NgInput({ required: true }) x!: string;
  @NgInput({ required: true }) y!: string;
  @NgInput({ required: true }) size!: string;
  @NgInput({ required: true }) time!: string;
  @NgInput() series?: string;
  @NgInput({ required: true }) label!: string;
  @NgInput() width?: number;
  @NgInput() height?: number;
  @NgInput('class') classInput?: string;

  /** Recomputed by `recompute()`; never derived in a template getter. */
  data: ScatterPlotDatum[] = [];
  xLabel = '';
  yLabel = '';
  steps: string[] = [];
  stepIndex = 0;
  safeIndex = 0;
  currentStep = '';
  maxStep = 0;
  playing = false;
  rootClass?: string;

  ngOnInit(): void {
    this.recompute();
  }

  ngOnChanges(): void {
    this.recompute();
  }

  ngOnDestroy(): void {
    // Inlined (not via stopTimer()) so the adapter-pattern guard reads the
    // teardown in this body.
    if (this.timer !== undefined) {
      clearInterval(this.timer);
      this.timer = undefined;
    }
    this.unsubscribe();
    this.signals?.destroy();
  }

  togglePlay(): void {
    this.playing = !this.playing;
    if (this.playing) this.startTimer();
    else this.stopTimer();
  }

  handleSlider(event: Event): void {
    this.stepIndex = Number((event.target as HTMLInputElement).value);
    this.playing = false;
    this.stopTimer();
    this.recompute();
  }

  private startTimer(): void {
    if (this.timer !== undefined) return;
    this.timer = setInterval(() => {
      if (this.steps.length > 0) {
        this.stepIndex = (this.stepIndex + 1) % this.steps.length;
        this.recompute();
      }
      this.changeDetector.markForCheck();
    }, 1000);
  }

  private stopTimer(): void {
    if (this.timer !== undefined) {
      clearInterval(this.timer);
      this.timer = undefined;
    }
  }

  private recompute(): void {
    if (!this.signals) return;
    void this.signals.state();
    const store = this.signals.store;
    this.steps = distinctSorted(store.applyCrossfilter(this.viewId), this.time);
    this.safeIndex = this.steps.length > 0 ? Math.min(this.stepIndex, this.steps.length - 1) : 0;
    this.currentStep = this.steps[this.safeIndex] ?? '';
    this.maxStep = Math.max(0, this.steps.length - 1);
    const frameRows = store
      .applyCrossfilter(this.viewId)
      .filter((row) => String(row[this.time]) === this.currentStep);
    const frame = buildBubbleFrame(store.model, frameRows, {
      x: this.x,
      y: this.y,
      size: this.size,
      series: this.series,
    });
    this.data = frame.data as ScatterPlotDatum[];
    this.xLabel = frame.xLabel;
    this.yLabel = frame.yLabel;
    this.rootClass = ['dataviz-animated-bubble', this.classInput].filter(Boolean).join(' ') || undefined;
  }
}
