// packages/dataviz-react/src/lib/DependencyWheelChart.tsx
import {
  DependencyWheelChart as DsDependencyWheelChart,
  type DependencyWheelChartLink,
} from '@sentropic/design-system-react';
import type { DashboardStore } from '@sentropic/dataviz-core';
import { buildDependencyWheelData } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type DependencyWheelChartProps = {
  store: DashboardStore;
  viewId: string;
  /** Field id whose value becomes the link's source node. */
  source: string;
  /** Field id whose value becomes the link's target node. */
  target: string;
  /** Field id whose numeric value becomes the link weight. */
  weight: string;
  /** Optional display labels per node id. */
  labels?: Record<string, string>;
  width?: number;
  height?: number;
  /** Accessible label for the chart (aria-label). */
  label: string;
  className?: string;
};

export function DependencyWheelChart({
  store,
  viewId,
  source,
  target,
  weight,
  labels,
  width,
  height,
  label,
  className,
}: DependencyWheelChartProps) {
  const state = useDashboard(store);
  void state;

  const data = buildDependencyWheelData(store.model, store.applyCrossfilter(viewId), {
    source,
    target,
    weight,
  });

  return (
    <DsDependencyWheelChart
      data={data as DependencyWheelChartLink[]}
      labels={labels}
      label={label}
      width={width}
      height={height}
      className={className}
    />
  );
}

// packages/dataviz-angular/src/lib/DependencyWheelChart.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Input as NgInput, inject } from '@angular/core';
import type { OnChanges, OnDestroy, OnInit } from '@angular/core';
import { DependencyWheelChart as DsDependencyWheelChart, type DependencyWheelChartLink } from '@sentropic/design-system-angular';
import { buildDependencyWheelData, type DashboardStore } from '@sentropic/dataviz-core';
import { toSignalStore, type AngularSignalStore } from '../adapter.js';

export type DependencyWheelChartProps = {
  store: DashboardStore;
  viewId: string;
  source: string;
  target: string;
  weight: string;
  labels?: Record<string, string>;
  width?: number;
  height?: number;
  label: string;
  class?: string;
};

/**
 * State wiring for a DS Angular DependencyWheelChart.
 * Generated from tools/dataviz-angular-port/descriptors.json — see that
 * directory's README before editing this file by hand.
 */
@Component({
  selector: 'st-dataviz-dependency-wheel-chart',
  standalone: true,
  imports: [DsDependencyWheelChart],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <st-dependency-wheel-chart
      [data]="data"
      [labels]="labels"
      [label]="label"
      [width]="width"
      [height]="height"
      [class]="classInput"
    ></st-dependency-wheel-chart>
  `,
})
export class DependencyWheelChart implements OnInit, OnChanges, OnDestroy {
  static readonly stComponentName = 'DependencyWheelChart';

  private readonly changeDetector = inject(ChangeDetectorRef);
  private signals?: AngularSignalStore;
  private unsubscribe: () => void = () => {};

  @NgInput({ required: true }) set store(value: DashboardStore) {
    if (this.signals) this.signals.replace(value);
    else this.signals = toSignalStore(value);
    this.unsubscribe();
    this.unsubscribe = value.subscribe(() => {
      this.recompute();
      this.changeDetector.markForCheck();
    });
  }

  get store(): DashboardStore {
    if (!this.signals) {
      throw new Error('DependencyWheelChart: store is required.');
    }
    return this.signals.store;
  }

  @NgInput({ required: true }) viewId!: string;
  @NgInput({ required: true }) source!: string;
  @NgInput({ required: true }) target!: string;
  @NgInput({ required: true }) weight!: string;
  @NgInput() labels?: Record<string, string>;
  @NgInput() width?: number;
  @NgInput() height?: number;
  @NgInput({ required: true }) label!: string;
  @NgInput('class') classInput?: string;

  /** Recomputed by `recompute()`; never derived in a template getter. */
  data: DependencyWheelChartLink[] = [];

  ngOnInit(): void {
    this.recompute();
  }

  ngOnChanges(): void {
    this.recompute();
  }

  ngOnDestroy(): void {
    this.unsubscribe();
    this.signals?.destroy();
  }

  private recompute(): void {
    if (!this.signals) return;
    void this.signals.state();
    this.data = buildDependencyWheelData(
      this.signals.store.model,
      this.signals.store.applyCrossfilter(this.viewId),
      {
        source: this.source,
        target: this.target,
        weight: this.weight,
      },
    );
  }
}
