// packages/dataviz-react/src/lib/FormatPanel.tsx
import { Checkbox, Input, NumberInput, Select } from '@sentropic/design-system-react';
import {
  updateAxisFormat,
  updateLegendFormat,
  updateMarkerFormat,
  type FormatAxisScale,
  type FormatMarkerShape,
  type FormatPanelState,
} from '@sentropic/dataviz-core';

export type FormatPanelProps = {
  value: FormatPanelState;
  onChange: (next: FormatPanelState) => void;
  label?: string;
  className?: string;
};

const SCALE_OPTIONS = [
  { value: 'linear', label: 'Linear' },
  { value: 'log', label: 'Log' },
];

const SHAPE_OPTIONS = [
  { value: 'circle', label: 'Circle' },
  { value: 'square', label: 'Square' },
  { value: 'diamond', label: 'Diamond' },
  { value: 'triangle', label: 'Triangle' },
];

function optionalNumber(value: string): number | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  const next = Number(trimmed);
  return Number.isFinite(next) ? next : null;
}

function scaleFrom(value: string): FormatAxisScale {
  return value === 'log' ? 'log' : 'linear';
}

function shapeFrom(value: string): FormatMarkerShape {
  if (value === 'square' || value === 'diamond' || value === 'triangle') return value;
  return 'circle';
}

export function FormatPanel({ value, onChange, label = 'Format', className }: FormatPanelProps) {
  return (
    <div role="group" aria-label={label} className={className}>
      {value.axes.map((axis) => (
        <div key={axis.id}>
          <NumberInput
            label={`Minimum ${axis.label}`}
            aria-label={`Minimum ${axis.label}`}
            value={axis.min ?? ''}
            onChange={(event) => onChange(updateAxisFormat(value, axis.id, { min: optionalNumber(event.currentTarget.value) }))}
          />
          <NumberInput
            label={`Maximum ${axis.label}`}
            aria-label={`Maximum ${axis.label}`}
            value={axis.max ?? ''}
            onChange={(event) => onChange(updateAxisFormat(value, axis.id, { max: optionalNumber(event.currentTarget.value) }))}
          />
          <Select
            label={`Echelle ${axis.label}`}
            aria-label={`Echelle ${axis.label}`}
            value={axis.scale}
            options={SCALE_OPTIONS}
            onChange={(event) => onChange(updateAxisFormat(value, axis.id, { scale: scaleFrom(event.currentTarget.value) }))}
          />
          <Checkbox
            label={`Inverser ${axis.label}`}
            aria-label={`Inverser ${axis.label}`}
            checked={axis.inverted}
            onChange={(event) => onChange(updateAxisFormat(value, axis.id, { inverted: event.currentTarget.checked }))}
          />
        </div>
      ))}

      {value.legends.map((legend) => (
        <div key={legend.id}>
          <Input
            label={`Titre ${legend.label}`}
            aria-label={`Titre ${legend.label}`}
            value={legend.title}
            onChange={(event) => onChange(updateLegendFormat(value, legend.id, { title: event.currentTarget.value }))}
          />
          <Checkbox
            label={`Afficher ${legend.label}`}
            aria-label={`Afficher ${legend.label}`}
            checked={legend.visible}
            onChange={(event) => onChange(updateLegendFormat(value, legend.id, { visible: event.currentTarget.checked }))}
          />
        </div>
      ))}

      {value.markers.map((marker) => (
        <div key={marker.id}>
          <Select
            label={`Forme ${marker.label}`}
            aria-label={`Forme ${marker.label}`}
            value={marker.shape}
            options={SHAPE_OPTIONS}
            onChange={(event) => onChange(updateMarkerFormat(value, marker.id, { shape: shapeFrom(event.currentTarget.value) }))}
          />
          <NumberInput
            label={`Taille ${marker.label}`}
            aria-label={`Taille ${marker.label}`}
            min={1}
            step={1}
            value={marker.size}
            onChange={(event) => onChange(updateMarkerFormat(value, marker.id, { size: optionalNumber(event.currentTarget.value) }))}
          />
          <Input
            label={`Couleur ${marker.label}`}
            aria-label={`Couleur ${marker.label}`}
            value={marker.color ?? ''}
            onChange={(event) => onChange(updateMarkerFormat(value, marker.id, { color: event.currentTarget.value || undefined }))}
          />
        </div>
      ))}
    </div>
  );
}

// packages/dataviz-angular/src/lib/FormatPanel.ts
import { ChangeDetectionStrategy, Component, Input as NgInput } from '@angular/core';
import type { OnChanges, OnInit } from '@angular/core';
import {
  Checkbox as DsCheckbox,
  Input as DsInput,
  NumberInput as DsNumberInput,
  Select as DsSelect,
  type SelectOption,
} from '@sentropic/design-system-angular';
import {
  updateAxisFormat,
  updateLegendFormat,
  updateMarkerFormat,
  type FormatAxisScale,
  type FormatMarkerShape,
  type FormatPanelState,
} from '@sentropic/dataviz-core';

export type FormatPanelProps = {
  value: FormatPanelState;
  onChange: (next: FormatPanelState) => void;
  label?: string;
  class?: string;
};

const SCALE_OPTIONS: SelectOption[] = [
  { value: 'linear', label: 'Linear' },
  { value: 'log', label: 'Log' },
];

const SHAPE_OPTIONS: SelectOption[] = [
  { value: 'circle', label: 'Circle' },
  { value: 'square', label: 'Square' },
  { value: 'diamond', label: 'Diamond' },
  { value: 'triangle', label: 'Triangle' },
];

function optionalNumber(value: unknown): number | null {
  const text = typeof value === 'string' ? value : typeof value === 'number' ? String(value) : '';
  const trimmed = text.trim();
  if (!trimmed) return null;
  const next = Number(trimmed);
  return Number.isFinite(next) ? next : null;
}

function scaleFrom(value: unknown): FormatAxisScale {
  return value === 'log' ? 'log' : 'linear';
}

function shapeFrom(value: unknown): FormatMarkerShape {
  if (value === 'square' || value === 'diamond' || value === 'triangle') return value;
  return 'circle';
}

/**
 * Controlled format editor for axes, legends and markers. Every edit calls
 * `onChange` with the core `updateAxisFormat` / `updateLegendFormat` /
 * `updateMarkerFormat` result, like Vue/React.
 *
 * tools/dataviz-angular-port refuses this shape: `setup()` holds no reactive
 * state, so there is no `void <state>.value` marker to anchor on (see
 * tools/dataviz-angular-port/README.md). The component is fully controlled —
 * it renders `value` directly and writes through `(modelValueChange)`, the
 * design-system event the lot 9 `RelativeDateFilter` port established — so
 * `recompute()` is intentionally a no-op: the adapter-pattern guard requires
 * the `ngOnInit`/`ngOnChanges` pair on every adapter, and this records that
 * there is nothing to derive.
 *
 * The DS `NumberInput`/`Select`/`Checkbox`/`Input` now forward `aria-label`
 * (like React/Vue), so the per-axis/legend/marker labels render on the
 * control alongside the visible `label` inputs.
 */
@Component({
  selector: 'st-dataviz-format-panel',
  standalone: true,
  imports: [DsCheckbox, DsInput, DsNumberInput, DsSelect],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div role="group" [attr.aria-label]="label" [class]="classInput">
      @for (axis of value.axes; track axis.id) {
        <div>
          <st-number-input
            [label]="'Minimum ' + axis.label"
            [aria-label]="'Minimum ' + axis.label"
            [modelValue]="axis.min ?? ''"
            (modelValueChange)="updateAxis(axis.id, { min: optionalNumber($event) })"
          ></st-number-input>
          <st-number-input
            [label]="'Maximum ' + axis.label"
            [aria-label]="'Maximum ' + axis.label"
            [modelValue]="axis.max ?? ''"
            (modelValueChange)="updateAxis(axis.id, { max: optionalNumber($event) })"
          ></st-number-input>
          <st-select
            [label]="'Echelle ' + axis.label"
            [aria-label]="'Echelle ' + axis.label"
            [modelValue]="axis.scale"
            [options]="scaleOptions"
            (modelValueChange)="updateAxis(axis.id, { scale: scaleFrom($event) })"
          ></st-select>
          <st-checkbox
            [label]="'Inverser ' + axis.label"
            [aria-label]="'Inverser ' + axis.label"
            [modelValue]="axis.inverted"
            [checked]="axis.inverted"
            (modelValueChange)="updateAxis(axis.id, { inverted: $event })"
          ></st-checkbox>
        </div>
      }
      @for (legend of value.legends; track legend.id) {
        <div>
          <st-input
            [label]="'Titre ' + legend.label"
            [aria-label]="'Titre ' + legend.label"
            [modelValue]="legend.title"
            (modelValueChange)="updateLegend(legend.id, { title: $event })"
          ></st-input>
          <st-checkbox
            [label]="'Afficher ' + legend.label"
            [aria-label]="'Afficher ' + legend.label"
            [modelValue]="legend.visible"
            [checked]="legend.visible"
            (modelValueChange)="updateLegend(legend.id, { visible: $event })"
          ></st-checkbox>
        </div>
      }
      @for (marker of value.markers; track marker.id) {
        <div>
          <st-select
            [label]="'Forme ' + marker.label"
            [aria-label]="'Forme ' + marker.label"
            [modelValue]="marker.shape"
            [options]="shapeOptions"
            (modelValueChange)="updateMarker(marker.id, { shape: shapeFrom($event) })"
          ></st-select>
          <st-number-input
            [label]="'Taille ' + marker.label"
            [aria-label]="'Taille ' + marker.label"
            [modelValue]="marker.size"
            [min]="1"
            [step]="1"
            (modelValueChange)="updateMarker(marker.id, { size: optionalNumber($event) })"
          ></st-number-input>
          <st-input
            [label]="'Couleur ' + marker.label"
            [aria-label]="'Couleur ' + marker.label"
            [modelValue]="marker.color ?? ''"
            (modelValueChange)="updateMarker(marker.id, { color: $event || undefined })"
          ></st-input>
        </div>
      }
    </div>
  `,
})
export class FormatPanel implements OnInit, OnChanges {
  static readonly stComponentName = 'FormatPanel';

  @NgInput({ required: true }) value!: FormatPanelState;
  @NgInput({ required: true }) onChange!: (next: FormatPanelState) => void;
  @NgInput() label = 'Format';
  @NgInput('class') classInput?: string;

  readonly scaleOptions = SCALE_OPTIONS;
  readonly shapeOptions = SHAPE_OPTIONS;

  ngOnInit(): void {
    this.recompute();
  }

  ngOnChanges(): void {
    this.recompute();
  }

  updateAxis(axisId: string, patch: Parameters<typeof updateAxisFormat>[2]): void {
    this.onChange(updateAxisFormat(this.value, axisId, patch));
  }

  updateLegend(legendId: string, patch: Parameters<typeof updateLegendFormat>[2]): void {
    this.onChange(updateLegendFormat(this.value, legendId, patch));
  }

  updateMarker(markerId: string, patch: Parameters<typeof updateMarkerFormat>[2]): void {
    this.onChange(updateMarkerFormat(this.value, markerId, patch));
  }

  optionalNumber(value: unknown): number | null {
    return optionalNumber(value);
  }

  scaleFrom(value: unknown): FormatAxisScale {
    return scaleFrom(value);
  }

  shapeFrom(value: unknown): FormatMarkerShape {
    return shapeFrom(value);
  }

  private recompute(): void {
    // Fully controlled: the template renders `value` directly, so there is
    // nothing to derive. The method exists because the adapter-pattern guard
    // requires every adapter to recompute from both ngOnInit and ngOnChanges.
  }
}
