// packages/components-angular/src/ColumnPyramidChart.ts
import { Component, Input as NgInput } from "@angular/core";

import { classNames } from "./classNames.js";

import { formatTick, niceTicks, scaleLinear } from "./chartScale.js";

export type ColumnPyramidChartTone =
  | "category1"
  | "category2"
  | "category3"
  | "category4"
  | "category5"
  | "category6"
  | "category7"
  | "category8";

export type ColumnPyramidChartDatum = {
  category: string;
  value: number;
  tone?: ColumnPyramidChartTone;
};

export type ColumnPyramidChartProps = {
  data: ColumnPyramidChartDatum[];
  width?: number;
  height?: number;
  label: string;
  /** Default tone for columns whose datum has no `tone`. */
  tone?: ColumnPyramidChartTone;
  class?: string;
};

const MARGIN = { top: 24, right: 16, bottom: 32, left: 44 } as const;

type Column = {
  datum: ColumnPyramidChartDatum;
  tone: ColumnPyramidChartTone;
  points: string;
  cx: number;
  cy: number;
  labelX: number;
  labelY: number;
  index: number;
};

type TickItem = {
  value: number;
  x1: number;
  x2: number;
  y: number;
};

@Component({
  selector: "st-column-pyramid-chart",
  standalone: true,
  template: `
    <div [attr.data-st-component]="componentName" [class]="hostClass">
      <div
        class="st-columnPyramidChart__visual"
        role="img"
        [attr.aria-label]="label"
        (pointermove)="handleVisualPointerMove($event)"
        (pointerleave)="handleLeave()"
      >
        <svg
          [attr.viewBox]="viewBox"
          preserveAspectRatio="xMidYMid meet"
          width="100%"
          height="100%"
          focusable="false"
          aria-hidden="true"
        >
          @for (tick of valueAxisTicks; track tick.value) {
            <line class="st-columnPyramidChart__grid" [attr.x1]="tick.x1" [attr.x2]="tick.x2" [attr.y1]="tick.y" [attr.y2]="tick.y"></line>
            <text
              class="st-columnPyramidChart__tickLabel"
              [attr.x]="margin.left - 6"
              [attr.y]="tick.y"
              text-anchor="end"
              dominant-baseline="middle"
            >{{ formatTickLabel(tick.value) }}</text>
          }

          <line class="st-columnPyramidChart__axis" [attr.x1]="margin.left" [attr.x2]="margin.left" [attr.y1]="margin.top" [attr.y2]="heightValue - margin.bottom"></line>
          <line class="st-columnPyramidChart__axis" [attr.x1]="margin.left" [attr.x2]="widthValue - margin.right" [attr.y1]="heightValue - margin.bottom" [attr.y2]="heightValue - margin.bottom"></line>

          @for (col of columns; track col.datum.category) {
            <text
              class="st-columnPyramidChart__categoryLabel"
              [attr.x]="col.labelX"
              [attr.y]="col.labelY"
              text-anchor="middle"
            >{{ col.datum.category }}</text>
          }

          @for (col of columns; track col.datum.category) {
            <polygon
              [class]="columnClass(col)"
              [attr.points]="col.points"
              [attr.data-chart-index]="col.index"
            ></polygon>
          }
        </svg>
      </div>

      <ul class="st-chartDataList" [attr.aria-label]="'Data values for ' + label">
        @for (item of dataValueItems; track $index) {
          <li>{{ item }}</li>
        }
      </ul>

      @if (hoveredColumn) {
        <div
          class="st-columnPyramidChart__tooltip"
          role="presentation"
          [style.left]="tooltipLeftPct(hoveredColumn)"
          [style.top]="tooltipTopPct(hoveredColumn)"
        >
          <span class="st-columnPyramidChart__tooltipLabel">{{ hoveredColumn.datum.category }}</span>
          <span class="st-columnPyramidChart__tooltipValue">{{ hoveredColumn.datum.value }}</span>
        </div>
      }
    </div>
  `,
})
export class ColumnPyramidChart {
  static readonly stComponentName = "ColumnPyramidChart";
  readonly componentName = "ColumnPyramidChart";
  readonly margin = MARGIN;

  private hoveredIndex: number | null = null;

  @NgInput() data: ColumnPyramidChartDatum[] = [];
  @NgInput() width?: number;
  @NgInput() height?: number;
  @NgInput() label = "";
  @NgInput() tone?: ColumnPyramidChartTone;
  @NgInput("class") classInput?: string;

  get hostClass(): string {
    return classNames("st-columnPyramidChart", this.classInput);
  }

  get widthValue(): number {
    return this.width ?? 480;
  }

  get heightValue(): number {
    return this.height ?? 280;
  }

  get viewBox(): string {
    return `0 0 ${this.widthValue} ${this.heightValue}`;
  }

  get plotWidth(): number {
    return Math.max(this.widthValue - MARGIN.left - MARGIN.right, 1);
  }

  get plotHeight(): number {
    return Math.max(this.heightValue - MARGIN.top - MARGIN.bottom, 1);
  }

  get defaultTone(): ColumnPyramidChartTone {
    return this.tone ?? "category1";
  }

  get validData(): ColumnPyramidChartDatum[] {
    return this.data.filter((d) => Number.isFinite(d.value) && d.value > 0);
  }

  get ticks(): number[] {
    const values = this.validData.map((d) => d.value);
    const maxRaw = Math.max(0, ...values);
    return niceTicks(0, maxRaw, 5);
  }

  get domainMin(): number {
    return this.ticks[0] ?? 0;
  }

  get domainMax(): number {
    return this.ticks[this.ticks.length - 1] ?? 1;
  }

  get valueAxisTicks(): TickItem[] {
    return this.ticks.map((tick) => ({
      value: tick,
      x1: MARGIN.left,
      x2: MARGIN.left + this.plotWidth,
      y: MARGIN.top + scaleLinear(tick, this.domainMin, this.domainMax, this.plotHeight, 0),
    }));
  }

  get columns(): Column[] {
    if (this.validData.length === 0) return [];
    const band = this.plotWidth / this.validData.length;
    const baseWidth = band * 0.7;
    const zeroY = MARGIN.top + scaleLinear(0, this.domainMin, this.domainMax, this.plotHeight, 0);
    return this.validData.map((d, i) => {
      const apexY = MARGIN.top + scaleLinear(d.value, this.domainMin, this.domainMax, this.plotHeight, 0);
      const cx = MARGIN.left + band * (i + 0.5);
      const leftX = cx - baseWidth / 2;
      const rightX = cx + baseWidth / 2;
      const points = `${leftX},${zeroY} ${rightX},${zeroY} ${cx},${apexY}`;
      return {
        datum: d,
        tone: (d.tone ?? this.defaultTone) as ColumnPyramidChartTone,
        points,
        cx,
        cy: apexY,
        labelX: cx,
        labelY: this.heightValue - MARGIN.bottom + 16,
        index: i,
      };
    });
  }

  get dataValueItems(): string[] {
    return this.validData.map((d) => `${d.category}: ${d.value}`);
  }

  get hoveredColumn(): Column | null {
    return this.hoveredIndex !== null ? (this.columns[this.hoveredIndex] ?? null) : null;
  }

  columnClass(col: Column): string {
    return classNames("st-columnPyramidChart__column", `st-columnPyramidChart__column--${col.tone}`);
  }

  formatTickLabel(value: number): string {
    return formatTick(value);
  }

  tooltipLeftPct(col: Column): string {
    return `${(col.cx / this.widthValue) * 100}%`;
  }

  tooltipTopPct(col: Column): string {
    return `${(col.cy / this.heightValue) * 100}%`;
  }

  handleVisualPointerMove(event: PointerEvent): void {
    const target = event.target as { getAttribute?: (name: string) => string | null } | null;
    const raw = Number(target?.getAttribute?.("data-chart-index"));
    this.hoveredIndex = Number.isInteger(raw) ? raw : null;
  }

  handleLeave(): void {
    this.hoveredIndex = null;
  }
}

// packages/components-react/src/ColumnPyramidChart.tsx
import React from "react";
import { classNames } from "./classNames.js";
import { ChartDataList, formatTick, niceTicks, scaleLinear } from "./chartScale.js";

export type ColumnPyramidChartTone =
  | "category1"
  | "category2"
  | "category3"
  | "category4"
  | "category5"
  | "category6"
  | "category7"
  | "category8";

export type ColumnPyramidChartDatum = {
  category: string;
  value: number;
  tone?: ColumnPyramidChartTone;
};

export type ColumnPyramidChartProps = Omit<React.HTMLAttributes<HTMLDivElement>, "className"> & {
  data: ColumnPyramidChartDatum[];
  width?: number;
  height?: number;
  label: string;
  /** Default tone for columns whose datum has no `tone`. */
  tone?: ColumnPyramidChartTone;
  className?: string;
};

const MARGIN = { top: 24, right: 16, bottom: 32, left: 44 };

export function ColumnPyramidChart({
  data = [],
  width = 480,
  height = 280,
  label,
  tone = "category1",
  className,
  ...rest
}: ColumnPyramidChartProps) {
  const [hoveredIndex, setHoveredIndex] = React.useState<number | null>(null);

  // Valid data: finite, strictly-positive value (a triangle sitting on the X
  // axis is only meaningful for a value > 0).
  const validData = data.filter((d) => Number.isFinite(d.value) && d.value > 0);

  const values = validData.map((d) => d.value);
  const minRaw = 0;
  const maxRaw = Math.max(0, ...values);
  const ticks = niceTicks(minRaw, maxRaw, 5);
  const domainMin = ticks[0];
  const domainMax = ticks[ticks.length - 1];
  const plotWidth = Math.max(width - MARGIN.left - MARGIN.right, 1);
  const plotHeight = Math.max(height - MARGIN.top - MARGIN.bottom, 1);

  const columns = React.useMemo(() => {
    if (validData.length === 0) return [];
    const band = plotWidth / validData.length;
    const baseWidth = band * 0.7;
    const zeroY = MARGIN.top + scaleLinear(0, domainMin, domainMax, plotHeight, 0);
    return validData.map((d, i) => {
      const apexY = MARGIN.top + scaleLinear(d.value, domainMin, domainMax, plotHeight, 0);
      const cx = MARGIN.left + band * (i + 0.5);
      const leftX = cx - baseWidth / 2;
      const rightX = cx + baseWidth / 2;
      // Triangle: wide base on the X axis, apex centred at the value height.
      const points = `${leftX},${zeroY} ${rightX},${zeroY} ${cx},${apexY}`;
      return {
        datum: d,
        tone: (d.tone ?? tone) as ColumnPyramidChartTone,
        points,
        cx,
        cy: apexY,
        labelX: cx,
        labelY: height - MARGIN.bottom + 16,
      };
    });
  }, [validData, plotWidth, plotHeight, domainMin, domainMax, height, tone]);

  const dataValueItems = validData.map((d) => `${d.category}: ${d.value}`);

  const valueAxisTicks = ticks.map((tick) => ({
    value: tick,
    x1: MARGIN.left,
    x2: MARGIN.left + plotWidth,
    y: MARGIN.top + scaleLinear(tick, domainMin, domainMax, plotHeight, 0),
  }));

  function handlePointerMove(event: React.PointerEvent) {
    const target = event.target;
    if (!(target instanceof Element)) {
      setHoveredIndex(null);
      return;
    }
    const index = Number(target.getAttribute("data-chart-index"));
    setHoveredIndex(Number.isInteger(index) ? index : null);
  }

  const hovered = hoveredIndex !== null ? columns[hoveredIndex] : undefined;

  return (
    <div {...rest} className={classNames("st-columnPyramidChart", className)}>
      <div
        className="st-columnPyramidChart__visual"
        role="img"
        aria-label={label}
        onPointerMove={handlePointerMove}
        onPointerLeave={() => setHoveredIndex(null)}
      >
        <svg
          viewBox={`0 0 ${width} ${height}`}
          preserveAspectRatio="xMidYMid meet"
          width="100%"
          height="100%"
          focusable="false"
          aria-hidden="true"
        >
          {/* gridlines + value axis ticks */}
          {valueAxisTicks.map((tick) => (
            <React.Fragment key={tick.value}>
              <line className="st-columnPyramidChart__grid" x1={tick.x1} x2={tick.x2} y1={tick.y} y2={tick.y} />
              <text
                className="st-columnPyramidChart__tickLabel"
                x={MARGIN.left - 6}
                y={tick.y}
                textAnchor="end"
                dominantBaseline="middle"
              >
                {formatTick(tick.value)}
              </text>
            </React.Fragment>
          ))}

          {/* axes */}
          <line
            className="st-columnPyramidChart__axis"
            x1={MARGIN.left}
            x2={MARGIN.left}
            y1={MARGIN.top}
            y2={height - MARGIN.bottom}
          />
          <line
            className="st-columnPyramidChart__axis"
            x1={MARGIN.left}
            x2={width - MARGIN.right}
            y1={height - MARGIN.bottom}
            y2={height - MARGIN.bottom}
          />

          {/* category labels */}
          {columns.map((col) => (
            <text
              key={`cat-${col.datum.category}`}
              className="st-columnPyramidChart__categoryLabel"
              x={col.labelX}
              y={col.labelY}
              textAnchor="middle"
            >
              {col.datum.category}
            </text>
          ))}

          {/* pyramid columns (decorative, inside aria-hidden SVG) */}
          {columns.map((col, i) => (
            <polygon
              key={`col-${col.datum.category}`}
              className={`st-columnPyramidChart__column st-columnPyramidChart__column--${col.tone}`}
              points={col.points}
              data-chart-index={i}
            />
          ))}
        </svg>
      </div>

      <ChartDataList label={label} items={dataValueItems} />

      {hovered ? (
        <div
          className="st-columnPyramidChart__tooltip"
          role="presentation"
          style={{
            left: `${(hovered.cx / width) * 100}%`,
            top: `${(hovered.cy / height) * 100}%`,
          }}
        >
          <span className="st-columnPyramidChart__tooltipLabel">{hovered.datum.category}</span>
          <span className="st-columnPyramidChart__tooltipValue">{hovered.datum.value}</span>
        </div>
      ) : null}
    </div>
  );
}
