// packages/components-angular/src/NavRail.ts
import { Component, EventEmitter, Input as NgInput, Output } from "@angular/core";

export interface NavRailItem {
  id: string;
  label: unknown;
  href?: string;
  active?: boolean;
  disabled?: boolean;
  badge?: unknown;
}

export type NavRailProps = {
  items?: NavRailItem[];
  label?: string;
  activeItemId?: string;
  class?: string;
};

@Component({
  selector: "st-nav-rail",
  standalone: true,
  template: `
    <nav [attr.data-st-component]="componentName" [attr.aria-label]="label" [class]="hostClass">
      <div class="st-navRail__items">
        @for (item of items; track item.id) {
          @if (item.href && !item.disabled) {
            <a [href]="item.href"
              class="st-navRail__item"
              [class.st-navRail__item--active]="isActive(item)"
              [attr.aria-current]="isActive(item) ? 'page' : null"
              [attr.title]="item.label"
              (click)="selectItem(item)">
              <span class="st-navRail__label">{{ item.label }}</span>
              @if (item.badge != null) { <span class="st-navRail__badge">{{ item.badge }}</span> }
            </a>
          } @else {
            <button type="button"
              class="st-navRail__item"
              [class.st-navRail__item--active]="isActive(item)"
              [disabled]="item.disabled || null"
              [attr.aria-current]="isActive(item) ? 'page' : null"
              [attr.title]="item.label"
              (click)="selectItem(item)">
              <span class="st-navRail__label">{{ item.label }}</span>
              @if (item.badge != null) { <span class="st-navRail__badge">{{ item.badge }}</span> }
            </button>
          }
        }
        <ng-content></ng-content>
      </div>
    </nav>
  `,
})
export class NavRail {
  static readonly stComponentName = "NavRail";
  readonly componentName = "NavRail";
  @NgInput() items: NavRailItem[] = [];
  @NgInput() label = "Primary navigation";
  @NgInput() activeItemId?: string;
  @NgInput("class") classInput?: string;

  @Output() readonly itemSelect = new EventEmitter<string>();

  get hostClass(): string {
    return ["st-navRail", this.classInput].filter(Boolean).join(" ");
  }

  isActive(item: NavRailItem): boolean {
    return item.active === true || item.id === this.activeItemId;
  }

  selectItem(item: NavRailItem): void {
    if (!item.disabled) this.itemSelect.emit(item.id);
  }
}

// packages/components-react/src/NavRail.tsx
import React from "react";
import { classNames } from "./classNames.js";

export interface NavRailItem {
  id: string;
  label: React.ReactNode;
  href?: string;
  active?: boolean;
  disabled?: boolean;
  badge?: React.ReactNode;
  icon?: React.ReactNode;
}

export type NavRailProps = React.HTMLAttributes<HTMLElement> & {
  items?: NavRailItem[];
  label?: string;
  activeItemId?: string;
  onItemSelect?: (id: string) => void;
  footer?: React.ReactNode;
};

export function NavRail({ items = [], label = "Primary navigation", activeItemId, onItemSelect, footer, className, children, ...rest }: NavRailProps) {
  return (
    <nav {...rest} className={classNames("st-navRail", className)} aria-label={label}>
      <div className="st-navRail__items">
        {items.map((item) => {
          const active = item.active === true || item.id === activeItemId;
          const content = <>{item.icon ? <span className="st-navRail__icon">{item.icon}</span> : null}<span className="st-navRail__label">{item.label}</span>{item.badge != null ? <span className="st-navRail__badge">{item.badge}</span> : null}</>;
          return item.href && !item.disabled ? (
            <a key={item.id} className={classNames("st-navRail__item", active && "st-navRail__item--active")} href={item.href} aria-current={active ? "page" : undefined} onClick={() => onItemSelect?.(item.id)}>{content}</a>
          ) : (
            <button key={item.id} className={classNames("st-navRail__item", active && "st-navRail__item--active")} type="button" disabled={item.disabled} aria-current={active ? "page" : undefined} onClick={() => !item.disabled && onItemSelect?.(item.id)}>{content}</button>
          );
        })}
        {children}
      </div>
      {footer ? <footer className="st-navRail__footer">{footer}</footer> : null}
    </nav>
  );
}
