// packages/components-svelte/src/lib/Stack.svelte
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { FlexAlign, FlexJustify } from "./Flex.svelte";

  export type StackProps = Omit<HTMLAttributes<HTMLElement>, "class"> & {
    /** Spacing scale step (0..12) mapped to `--st-spacing-*`. */
    gap?: number;
    align?: FlexAlign;
    justify?: FlexJustify;
    as?: string;
    class?: string;
    children?: Snippet;
  };
</script>

<script lang="ts">
  import Flex from "./Flex.svelte";

  let {
    gap,
    align,
    justify,
    as = "div",
    class: className,
    children,
    ...rest
  }: StackProps = $props();

  const classes = $derived(["st-stack", className].filter(Boolean).join(" "));
</script>

<Flex {...rest} {as} {gap} {align} {justify} direction="column" class={classes}>
  {@render children?.()}
</Flex>

// packages/components-react/src/Stack.tsx
import React from "react";
import { classNames } from "./classNames.js";
import { Flex } from "./Flex.js";
import type { FlexAlign, FlexJustify } from "./Flex.js";

export type StackProps = Omit<React.HTMLAttributes<HTMLElement>, "className"> & {
  /** Spacing scale step (0..12) mapped to `--st-spacing-*`. */
  gap?: number;
  align?: FlexAlign;
  justify?: FlexJustify;
  as?: string;
  className?: string;
};

export const Stack = React.forwardRef<HTMLElement, StackProps>(
  ({ gap, align, justify, as = "div", className, children, ...rest }, ref) => (
    <Flex
      {...rest}
      ref={ref}
      as={as}
      gap={gap}
      align={align}
      justify={justify}
      direction="column"
      className={classNames("st-stack", className)}
    >
      {children}
    </Flex>
  ),
);

Stack.displayName = "Stack";
