// packages/dataviz-react/src/lib/AnomalySwimLaneChart.tsx
import {
  AnomalySwimLaneChart as DsAnomalySwimLaneChart,
  type AnomalySwimLaneSeries,
} from '@sentropic/design-system-react';
import type { DashboardStore } from '@sentropic/dataviz-core';
import { buildAnomalySwimLaneData } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type AnomalySwimLaneChartProps = {
  store: DashboardStore;
  viewId: string;
  /** Field id whose value groups rows into lanes. */
  job: string;
  /** Field id whose numeric value becomes the bucket timestamp/index. */
  at: string;
  /** Field id whose numeric value encodes the anomaly score. */
  score: string;
  /** Maximum score value for the scale. */
  max?: number;
  /** Accessible label for the chart (aria-label). */
  label?: string;
  width?: number;
  height?: number;
  size?: number;
  className?: string;
};

export function AnomalySwimLaneChart({
  store,
  viewId,
  job,
  at,
  score,
  max,
  label,
  width,
  height,
  size,
  className,
}: AnomalySwimLaneChartProps) {
  const storeState = useDashboard(store);
  void storeState;

  const data = buildAnomalySwimLaneData(store.model, store.applyCrossfilter(viewId), {
    job,
    at,
    score,
  });

  return (
    <DsAnomalySwimLaneChart
      data={data as AnomalySwimLaneSeries[]}
      max={max}
      label={label}
      width={width}
      height={height}
      size={size}
      className={className}
    />
  );
}

// packages/dataviz-svelte/src/lib/AnomalySwimLaneChart.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type AnomalySwimLaneChartProps = {
    store: DashboardStore;
    viewId: string;
    /** Field id whose value groups rows into lanes. */
    job: string;
    /** Field id whose numeric value becomes the bucket timestamp/index. */
    at: string;
    /** Field id whose numeric value encodes the anomaly score. */
    score: string;
    /** Maximum score value for the scale. */
    max?: number;
    /** Accessible label for the chart (aria-label). */
    label?: string;
    width?: number;
    height?: number;
    size?: number;
    class?: string;
  };
</script>

<script lang="ts">
  import { AnomalySwimLaneChart as DsAnomalySwimLaneChart } from '@sentropic/design-system-svelte';
  import type { AnomalySwimLaneSeries } from '@sentropic/design-system-svelte';
  import { buildAnomalySwimLaneData } from '@sentropic/dataviz-core';
  import { useDashboard } from '../adapter.js';

  let {
    store,
    viewId,
    job,
    at,
    score,
    max,
    label,
    width,
    height,
    size,
    class: className,
  }: AnomalySwimLaneChartProps = $props();

  const dash = $derived(useDashboard(store));
  const data = $derived.by(() => {
    void $dash;
    return buildAnomalySwimLaneData(store.model, store.applyCrossfilter(viewId), {
      job,
      at,
      score,
    });
  });
</script>

<DsAnomalySwimLaneChart
  data={data as AnomalySwimLaneSeries[]}
  {max}
  {label}
  {width}
  {height}
  {size}
  class={className}
/>
