// packages/dataviz-react/src/lib/SankeyChart.tsx
import { SankeyChart as DsSankeyChart } from '@sentropic/design-system-react';
import type { DashboardStore } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';
import { buildSafeFlowModel } from './partOfWholeData.js';

export type SankeyChartProps = {
  store: DashboardStore;
  viewId: string;
  source: string;
  target: string;
  measure: string;
  width?: number;
  height?: number;
  label: string;
  className?: string;
};

export function SankeyChart({
  store,
  viewId,
  source,
  target,
  measure,
  width,
  height,
  label,
  className,
}: SankeyChartProps) {
  const state = useDashboard(store);
  void state;

  const model = buildSafeFlowModel(store.model, store.applyCrossfilter(viewId), { source, target, measure });

  return (
    <DsSankeyChart
      nodes={model.nodes}
      links={model.links}
      label={label}
      width={width}
      height={height}
      className={className}
    />
  );
}

// packages/dataviz-svelte/src/lib/SankeyChart.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type SankeyChartProps = {
    store: DashboardStore;
    viewId: string;
    source: string;
    target: string;
    measure: string;
    width?: number;
    height?: number;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { SankeyChart as DsSankeyChart } from '@sentropic/design-system-svelte';
  import { useDashboard } from '../adapter.js';
  import { buildSafeFlowModel } from './partOfWholeData.js';

  let {
    store,
    viewId,
    source,
    target,
    measure,
    width,
    height,
    label,
    class: className,
  }: SankeyChartProps = $props();

  const dash = $derived(useDashboard(store));
  const flow = $derived.by(() => {
    void $dash;
    return buildSafeFlowModel(store.model, store.applyCrossfilter(viewId), { source, target, measure });
  });
</script>

<DsSankeyChart nodes={flow.nodes} links={flow.links} {label} {width} {height} class={className} />
