// packages/components-svelte/src/lib/Form.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLFormAttributes } from "svelte/elements";

  type FormStatus = "idle" | "submitting" | "submitted" | "error";

  type FormProps = Omit<HTMLFormAttributes, "class" | "onsubmit"> & {
    onsubmit?: (event: SubmitEvent) => void | Promise<void>;
    helperText?: string;
    errorText?: string;
    successText?: string;
    submitting?: boolean;
    noNoscript?: boolean;
    class?: string;
    children: Snippet;
  };

  let {
    onsubmit,
    helperText,
    errorText,
    successText,
    submitting = $bindable(false),
    noNoscript = false,
    class: className,
    children,
    ...rest
  }: FormProps = $props();

  let status = $state<FormStatus>("idle");
  let internalError = $state<string | undefined>(undefined);

  const classes = () => ["st-form", className].filter(Boolean).join(" ");

  async function handleSubmit(event: SubmitEvent) {
    if (!onsubmit) return;
    event.preventDefault();
    internalError = undefined;
    status = "submitting";
    submitting = true;
    try {
      await onsubmit(event);
      status = "submitted";
    } catch (err) {
      status = "error";
      internalError = err instanceof Error ? err.message : String(err);
    } finally {
      submitting = false;
    }
  }

  const resolvedErrorText = () => errorText ?? internalError;
  const showError = () => status === "error" && Boolean(resolvedErrorText());
  const showSuccess = () => status === "submitted" && Boolean(successText);
  const showHelper = () =>
    Boolean(helperText) && !showError() && !showSuccess();
</script>

<form
  {...rest}
  class={classes()}
  onsubmit={handleSubmit}
  aria-busy={status === "submitting" ? "true" : undefined}
>
  <div class="st-form__body">
    {@render children()}
  </div>
  {#if showError()}
    <p class="st-form__message st-form__message--error" role="alert">
      {resolvedErrorText()}
    </p>
  {:else if showSuccess()}
    <p class="st-form__message st-form__message--success" role="status">
      {successText}
    </p>
  {:else if showHelper()}
    <p class="st-form__message st-form__message--help">{helperText}</p>
  {/if}
  {#if !noNoscript}
    <noscript>
      <p class="st-form__message st-form__message--error">
        JavaScript is required to submit this form.
      </p>
    </noscript>
  {/if}
</form>

<style>
  .st-form {
    display: grid;
    gap: var(--st-component-form-gap, 1rem);
    width: 100%;
  }

  .st-form__body {
    display: grid;
    gap: var(--st-component-form-fieldGap, 1rem);
  }

  .st-form__message {
    font-size: 0.8125rem;
    line-height: 1.4;
    margin: 0;
  }

  .st-form__message--help {
    color: var(--st-component-form-helpText, var(--st-semantic-text-secondary));
  }

  .st-form__message--error {
    color: var(--st-component-form-errorText, var(--st-semantic-feedback-error));
  }

  .st-form__message--success {
    color: var(--st-component-form-successText, var(--st-semantic-feedback-success));
  }
</style>

// packages/components-angular/src/Form.ts
import { Component, EventEmitter, Input as NgInput, Output } from "@angular/core";

import { classNames } from "./classNames.js";

export type FormStatus = "idle" | "submitting" | "submitted" | "error";

export type FormProps = {
  helperText?: string;
  errorText?: string;
  successText?: string;
  submitting?: boolean;
  noNoscript?: boolean;
  class?: string;
};

@Component({
  selector: "st-form",
  standalone: true,
  template: `
    <form
      [attr.data-st-component]="componentName"
      [class]="hostClass"
      [attr.aria-busy]="submitting ? 'true' : null"
      (submit)="onSubmit($event)"
    >
      <div class="st-form__body">
        <ng-content></ng-content>
      </div>
      @if (showError) {
        <p class="st-form__message st-form__message--error" role="alert">{{ errorText }}</p>
      } @else if (showSuccess) {
        <p class="st-form__message st-form__message--success" role="status">{{ successText }}</p>
      } @else if (showHelper) {
        <p class="st-form__message st-form__message--help">{{ helperText }}</p>
      }
      @if (!noNoscript) {
        <noscript>
          <p class="st-form__message st-form__message--error">
            JavaScript is required to submit this form.
          </p>
        </noscript>
      }
    </form>
  `,
})
export class Form {
  static readonly stComponentName = "Form";
  readonly componentName = "Form";

  @NgInput() helperText?: string;
  @NgInput() errorText?: string;
  @NgInput() successText?: string;
  @NgInput() submitting?: boolean;
  @NgInput() noNoscript?: boolean;
  @NgInput("class") classInput?: string;

  @Output() readonly submit = new EventEmitter<SubmitEvent>();

  get showError(): boolean {
    return Boolean(this.errorText);
  }

  get showSuccess(): boolean {
    return !this.showError && Boolean(this.successText);
  }

  get showHelper(): boolean {
    return !this.showError && !this.showSuccess && Boolean(this.helperText);
  }

  get hostClass(): string {
    return classNames("st-form", this.classInput);
  }

  onSubmit(event: Event): void {
    this.submit.emit(event as SubmitEvent);
  }
}
