// packages/components-svelte/src/lib/InlineLoading.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";

  type InlineLoadingProps = Omit<HTMLAttributes<HTMLDivElement>, "class"> & {
    label?: string;
    status?: "active" | "success" | "error" | "inactive";
    class?: string;
  };

  let {
    label,
    status = "active",
    class: className,
    ...rest
  }: InlineLoadingProps = $props();

  const classes = () =>
    ["st-inlineLoading", `st-inlineLoading--${status}`, className].filter(Boolean).join(" ");

  const role = () => (status === "error" ? "alert" : "status");
</script>

<div {...rest} class={classes()} role={role()} aria-live="polite">
  <span class="st-inlineLoading__icon" aria-hidden="true">
    {#if status === "active"}
      <svg viewBox="0 0 16 16" width="16" height="16">
        <circle cx="8" cy="8" r="6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-opacity="0.2" />
        <path d="M14 8a6 6 0 0 0-6-6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round">
          <animateTransform attributeName="transform" type="rotate" from="0 8 8" to="360 8 8" dur="0.9s" repeatCount="indefinite" />
        </path>
      </svg>
    {:else if status === "success"}
      <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" width="14" height="14">
        <path d="m3 8 3.5 3.5L13 5" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    {:else if status === "error"}
      <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" width="14" height="14">
        <path d="M4 4l8 8M12 4l-8 8" stroke-linecap="round" />
      </svg>
    {/if}
  </span>
  {#if label}<span class="st-inlineLoading__label">{label}</span>{/if}
</div>

<style>
  .st-inlineLoading {
    align-items: center;
    color: var(--st-semantic-text-secondary);
    display: inline-flex;
    font-size: 0.875rem;
    gap: 0.5rem;
  }

  .st-inlineLoading__icon {
    align-items: center;
    display: inline-flex;
    justify-content: center;
  }

  .st-inlineLoading--active .st-inlineLoading__icon {
    color: var(--st-semantic-action-primary);
  }

  .st-inlineLoading--success {
    color: var(--st-semantic-feedback-success);
  }

  .st-inlineLoading--error {
    color: var(--st-semantic-feedback-error);
  }

  .st-inlineLoading--inactive {
    color: var(--st-semantic-text-muted);
  }

  @media (prefers-reduced-motion: reduce) {
    .st-inlineLoading__icon svg path animateTransform {
      display: none;
    }
  }
</style>

// packages/components-angular/src/InlineLoading.ts
import { Component, Input as NgInput } from "@angular/core";

import { classNames } from "./classNames.js";

export type InlineLoadingStatus = "active" | "inactive" | "success" | "error";

export type InlineLoadingProps = {
  label?: unknown;
  status?: InlineLoadingStatus;
  locale?: string;
  class?: string;
};

@Component({
  selector: "st-inline-loading",
  standalone: true,
  styles: [":host { display: contents; }"],
  template: `
    <div
      [attr.data-st-component]="componentName"
      [class]="hostClass"
      [attr.role]="role"
      [attr.aria-label]="accessibleLabel"
      aria-live="polite"
    >
      <span class="st-inlineLoading__icon" aria-hidden="true">
        @if (resolvedStatus === 'active') {
          <span class="st-inlineLoading__spinner">
            <svg viewBox="0 0 24 24" width="16" height="16" fill="none" aria-hidden="true">
              <circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="2" opacity="0.25"/>
              <path d="M12 3a9 9 0 0 1 9 9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            </svg>
          </span>
        } @else if (resolvedStatus === 'success') {
          <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <circle cx="12" cy="12" r="10"/>
            <path d="m9 12 2 2 4-4"/>
          </svg>
        } @else if (resolvedStatus === 'error') {
          <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <circle cx="12" cy="12" r="10"/>
            <line x1="12" y1="8" x2="12" y2="12"/>
            <line x1="12" y1="16" x2="12.01" y2="16"/>
          </svg>
        }
      </span>
      @if (label) { <span class="st-inlineLoading__label">{{ label }}</span> }
    </div>
  `,
})
export class InlineLoading {
  static readonly stComponentName = "InlineLoading";
  readonly componentName = "InlineLoading";
  @NgInput() label?: unknown;
  @NgInput() status?: InlineLoadingStatus;
  @NgInput() locale = "fr-FR";
  @NgInput("class") classInput?: string;

  get resolvedStatus(): InlineLoadingStatus {
    return this.status ?? "active";
  }

  get hostClass(): string {
    return classNames(
      "st-inlineLoading",
      `st-inlineLoading--${this.resolvedStatus}`,
      this.classInput,
    );
  }

  get role(): string {
    return this.resolvedStatus === "error" ? "alert" : "status";
  }

  private get isFr(): boolean {
    return this.locale.toLowerCase().startsWith("fr");
  }

  private get fallbackLabel(): string {
    const labels: Record<InlineLoadingStatus, string> = this.isFr
      ? { active: "Chargement", success: "Terminé", error: "Erreur", inactive: "Inactif" }
      : { active: "Loading", success: "Completed", error: "Error", inactive: "Inactive" };
    return labels[this.resolvedStatus];
  }

  get accessibleLabel(): string | null {
    return this.label ? null : this.fallbackLabel;
  }
}
