// packages/components-svelte/src/lib/NavDrawer.svelte
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { NavShellSide } from "./NavShell.svelte";

  export interface NavDrawerProps {
    title?: string;
    subtitle?: string;
    label?: string;
    search?: Snippet;
    footer?: Snippet;
    children: Snippet;
    open?: boolean;
    side?: NavShellSide;
    class?: string;
  }
</script>

<script lang="ts">
  import NavShell from "./NavShell.svelte";

  let {
    title,
    subtitle,
    label,
    search,
    footer,
    children,
    open = $bindable(false),
    side = "left",
    class: className
  }: NavDrawerProps = $props();
</script>

<NavShell
  bind:open
  variant="drawer"
  {title}
  {subtitle}
  {label}
  {search}
  {footer}
  {side}
  class={["st-navDrawer", className].filter(Boolean).join(" ")}
>
  {@render children()}
</NavShell>

// packages/components-angular/src/NavDrawer.ts
import { Component, Input as NgInput } from "@angular/core";
import type { NavShellSide } from "./NavShell.js";
import { Drawer } from "./Drawer.js";

export type NavDrawerProps = {
  title?: string;
  label?: string;
  open?: boolean;
  side?: NavShellSide;
  class?: string;
};

@Component({
  selector: "st-nav-drawer",
  standalone: true,
  imports: [Drawer],
  template: `
    <st-drawer [open]="open" [title]="title || label || 'Navigation'" [placement]="side" [class]="hostClass">
      <ng-content></ng-content>
    </st-drawer>
  `,
})
export class NavDrawer {
  static readonly stComponentName = "NavDrawer";
  readonly componentName = "NavDrawer";
  @NgInput() title?: string;
  @NgInput() label?: string;
  @NgInput() open = false;
  @NgInput() side: NavShellSide = "left";
  @NgInput("class") classInput?: string;

  get hostClass(): string {
    return ["st-navDrawer", "st-navShell", "st-navShell--drawer", this.classInput].filter(Boolean).join(" ");
  }
}
