// packages/components-react/src/Notification.tsx
import React from "react";
import { classNames } from "./classNames.js";

export type NotificationProps = Omit<React.HTMLAttributes<HTMLElement>, "className" | "title"> & {
  tone?: "info" | "success" | "warning" | "error";
  title: string;
  message?: string;
  dismissible?: boolean;
  dismissLabel?: string;
  locale?: string;
  onDismiss?: () => void;
  className?: string;
  actions?: React.ReactNode;
  children?: React.ReactNode;
};

export const Notification = React.forwardRef<HTMLElement, NotificationProps>(
  (
    {
      tone = "info",
      title,
      message,
      dismissible = false,
      dismissLabel,
      locale = "fr-FR",
      onDismiss,
      className,
      actions,
      children,
      ...rest
    },
    ref,
  ) => {
    const isFr = (locale ?? "fr-FR").toLowerCase().startsWith("fr");
    const resolvedDismissLabel = dismissLabel ?? (isFr ? "Fermer" : "Dismiss");
    const canDismiss = dismissible && typeof onDismiss === "function";
    const role = tone === "error" ? "alert" : "status";

    return (
      <section
        {...rest}
        ref={ref}
        className={classNames("st-notification", `st-notification--${tone}`, className)}
        role={role}
      >
        <div className="st-notification__content">
          <h2 className="st-notification__title">{title}</h2>
          {message ? <p className="st-notification__message">{message}</p> : null}
          {children}
        </div>
        <div className="st-notification__meta">
          {actions ? <div className="st-notification__actions">{actions}</div> : null}
          {canDismiss ? (
            <button
              type="button"
              className="st-notification__close"
              aria-label={resolvedDismissLabel}
              title={resolvedDismissLabel}
              onClick={() => onDismiss?.()}
            >
              ×
            </button>
          ) : null}
        </div>
      </section>
    );
  },
);

Notification.displayName = "Notification";

// packages/components-angular/src/Notification.ts
import { Component, EventEmitter, Input as NgInput, Output } from "@angular/core";

import { classNames } from "./classNames.js";

export type NotificationTone = "info" | "success" | "warning" | "error";

export type NotificationProps = {
  tone?: NotificationTone;
  title: string;
  message?: string;
  dismissible?: boolean;
  dismissLabel?: string;
  locale?: string;
  class?: string;
};

@Component({
  selector: "st-notification",
  standalone: true,
  template: `
    <section
      [attr.data-st-component]="componentName"
      [class]="hostClass"
      [attr.role]="tone === 'error' ? 'alert' : 'status'"
    >
      <div class="st-notification__content">
        <h2 class="st-notification__title">{{ title }}</h2>
        @if (message) {
          <p class="st-notification__message">{{ message }}</p>
        }
        <ng-content></ng-content>
      </div>
      <div class="st-notification__meta">
        <div class="st-notification__actions">
          <ng-content select="[slot='actions']"></ng-content>
        </div>
        @if (dismissible) {
          <button
            type="button"
            class="st-notification__close"
            [attr.aria-label]="resolvedDismissLabel"
            [attr.title]="resolvedDismissLabel"
            (click)="dismiss.emit()"
          >&#xD7;</button>
        }
      </div>
    </section>
  `,
})
export class Notification {
  static readonly stComponentName = "Notification";
  readonly componentName = "Notification";

  @NgInput() tone?: NotificationTone;
  @NgInput() title!: string;
  @NgInput() message?: string;
  @NgInput() dismissible?: boolean;
  @NgInput() dismissLabel?: string;
  @NgInput() locale?: string;
  @NgInput("class") classInput?: string;

  get resolvedDismissLabel(): string {
    const isFr = (this.locale ?? "fr-FR").toLowerCase().startsWith("fr");
    return this.dismissLabel ?? (isFr ? "Fermer" : "Dismiss");
  }

  @Output() readonly dismiss = new EventEmitter<void>();

  get hostClass(): string {
    return classNames(
      "st-notification",
      this.tone && `st-notification--${this.tone}`,
      this.classInput,
    );
  }
}
