// packages/dataviz-angular/src/lib/AreaRangeChart.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Input as NgInput, inject } from '@angular/core';
import type { OnChanges, OnDestroy, OnInit } from '@angular/core';
import { AreaRangeChart as DsAreaRangeChart, type AreaRangeChartDatum } from '@sentropic/design-system-angular';
import { buildAreaRangeData, type DashboardStore } from '@sentropic/dataviz-core';
import { toSignalStore, type AngularSignalStore } from '../adapter.js';

export type AreaRangeChartProps = {
  store: DashboardStore;
  viewId: string;
  x_field: string;
  low: string;
  high: string;
  tone?: string;
  width?: number;
  height?: number;
  label: string;
  class?: string;
};

/**
 * State wiring for a DS Angular AreaRangeChart.
 * Generated from tools/dataviz-angular-port/descriptors.json — see that
 * directory's README before editing this file by hand.
 */
@Component({
  selector: 'st-dataviz-area-range-chart',
  standalone: true,
  imports: [DsAreaRangeChart],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <st-area-range-chart
      [data]="data"
      [label]="label"
      [width]="width"
      [height]="height"
      [tone]="tone"
      [class]="classInput"
    ></st-area-range-chart>
  `,
})
export class AreaRangeChart implements OnInit, OnChanges, OnDestroy {
  static readonly stComponentName = 'AreaRangeChart';

  private readonly changeDetector = inject(ChangeDetectorRef);
  private signals?: AngularSignalStore;
  private unsubscribe: () => void = () => {};

  @NgInput({ required: true }) set store(value: DashboardStore) {
    if (this.signals) this.signals.replace(value);
    else this.signals = toSignalStore(value);
    this.unsubscribe();
    this.unsubscribe = value.subscribe(() => {
      this.recompute();
      this.changeDetector.markForCheck();
    });
  }

  get store(): DashboardStore {
    if (!this.signals) {
      throw new Error('AreaRangeChart: store is required.');
    }
    return this.signals.store;
  }

  @NgInput({ required: true }) viewId!: string;
  @NgInput({ required: true }) x_field!: string;
  @NgInput({ required: true }) low!: string;
  @NgInput({ required: true }) high!: string;
  @NgInput() tone?: string;
  @NgInput() width?: number;
  @NgInput() height?: number;
  @NgInput({ required: true }) label!: string;
  @NgInput('class') classInput?: string;

  /** Recomputed by `recompute()`; never derived in a template getter. */
  data: AreaRangeChartDatum[] = [];

  ngOnInit(): void {
    this.recompute();
  }

  ngOnChanges(): void {
    this.recompute();
  }

  ngOnDestroy(): void {
    this.unsubscribe();
    this.signals?.destroy();
  }

  private recompute(): void {
    if (!this.signals) return;
    void this.signals.state();
    this.data = buildAreaRangeData(
      this.signals.store.model,
      this.signals.store.applyCrossfilter(this.viewId),
      {
        x: this.x_field,
        low: this.low,
        high: this.high,
      },
    );
  }
}

// packages/dataviz-react/src/lib/AreaRangeChart.tsx
import {
  AreaRangeChart as DsAreaRangeChart,
  type AreaRangeChartDatum,
} from '@sentropic/design-system-react';
import type { DashboardStore } from '@sentropic/dataviz-core';
import { buildAreaRangeData } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type AreaRangeChartProps = {
  store: DashboardStore;
  viewId: string;
  /** Field id whose value becomes the x-axis position. */
  x_field: string;
  /** Field id whose numeric value becomes the low boundary. */
  low: string;
  /** Field id whose numeric value becomes the high boundary. */
  high: string;
  tone?: string;
  width?: number;
  height?: number;
  /** Accessible label for the chart (aria-label). */
  label: string;
  className?: string;
};

export function AreaRangeChart({
  store,
  viewId,
  x_field,
  low,
  high,
  tone,
  width,
  height,
  label,
  className,
}: AreaRangeChartProps) {
  const state = useDashboard(store);
  void state;

  const data = buildAreaRangeData(store.model, store.applyCrossfilter(viewId), {
    x: x_field,
    low,
    high,
  });

  return (
    <DsAreaRangeChart
      data={data as AreaRangeChartDatum[]}
      label={label}
      width={width}
      height={height}
      tone={tone as any}
      className={className}
    />
  );
}
