// packages/dataviz-angular/src/lib/EventFeedPanel.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Input as NgInput, inject } from '@angular/core';
import type { OnChanges, OnDestroy, OnInit } from '@angular/core';
import { EventFeedPanel as DsEventFeedPanel, type EventFeedPanelEvent } from '@sentropic/design-system-angular';
import { buildEventFeedData, type DashboardStore } from '@sentropic/dataviz-core';
import { toSignalStore, type AngularSignalStore } from '../adapter.js';

export type EventFeedPanelProps = {
  store: DashboardStore;
  viewId: string;
  at: string;
  type: string;
  severity: string;
  message: string;
  maxHeight?: number;
  height?: number;
  label?: string;
  class?: string;
};

/**
 * State wiring for a DS Angular EventFeedPanel.
 * Generated from tools/dataviz-angular-port/descriptors.json — see that
 * directory's README before editing this file by hand.
 */
@Component({
  selector: 'st-dataviz-event-feed-panel',
  standalone: true,
  imports: [DsEventFeedPanel],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <st-event-feed-panel
      [data]="data"
      [label]="label"
      [maxHeight]="maxHeight"
      [height]="height"
      [class]="classInput"
    ></st-event-feed-panel>
  `,
})
export class EventFeedPanel implements OnInit, OnChanges, OnDestroy {
  static readonly stComponentName = 'EventFeedPanel';

  private readonly changeDetector = inject(ChangeDetectorRef);
  private signals?: AngularSignalStore;
  private unsubscribe: () => void = () => {};

  @NgInput({ required: true }) set store(value: DashboardStore) {
    if (this.signals) this.signals.replace(value);
    else this.signals = toSignalStore(value);
    this.unsubscribe();
    this.unsubscribe = value.subscribe(() => {
      this.recompute();
      this.changeDetector.markForCheck();
    });
  }

  get store(): DashboardStore {
    if (!this.signals) {
      throw new Error('EventFeedPanel: store is required.');
    }
    return this.signals.store;
  }

  @NgInput({ required: true }) viewId!: string;
  @NgInput({ required: true }) at!: string;
  @NgInput({ required: true }) type!: string;
  @NgInput({ required: true }) severity!: string;
  @NgInput({ required: true }) message!: string;
  @NgInput() maxHeight?: number;
  @NgInput() height?: number;
  @NgInput() label?: string;
  @NgInput('class') classInput?: string;

  /** Recomputed by `recompute()`; never derived in a template getter. */
  data: EventFeedPanelEvent[] = [];

  ngOnInit(): void {
    this.recompute();
  }

  ngOnChanges(): void {
    this.recompute();
  }

  ngOnDestroy(): void {
    this.unsubscribe();
    this.signals?.destroy();
  }

  private recompute(): void {
    if (!this.signals) return;
    void this.signals.state();
    this.data = buildEventFeedData(
      this.signals.store.model,
      this.signals.store.applyCrossfilter(this.viewId),
      {
        at: this.at,
        type: this.type,
        severity: this.severity,
        message: this.message,
      },
    );
  }
}

// packages/dataviz-react/src/lib/EventFeedPanel.tsx
import {
  EventFeedPanel as DsEventFeedPanel,
  type EventFeedPanelEvent as DsEventFeedPanelEvent,
} from '@sentropic/design-system-react';
import type { DashboardStore } from '@sentropic/dataviz-core';
import { buildEventFeedData } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type EventFeedPanelProps = {
  store: DashboardStore;
  viewId: string;
  /** Field id whose numeric value becomes the event timestamp (epoch ms). */
  at: string;
  /** Field id whose value becomes the event type/category (string-coerced). */
  type: string;
  /** Field id whose value becomes the severity (string-coerced, default 'info'). */
  severity: string;
  /** Field id whose value becomes the displayed message (string-coerced). */
  message: string;
  /** Max height in px (triggers vertical scroll). */
  maxHeight?: number;
  /** Fixed height in px (alias of maxHeight). */
  height?: number;
  /** Accessible label for the feed (aria-label). */
  label?: string;
  className?: string;
};

export function EventFeedPanel({
  store,
  viewId,
  at,
  type,
  severity,
  message,
  maxHeight,
  height,
  label,
  className,
}: EventFeedPanelProps) {
  const state = useDashboard(store);
  void state;

  const data = buildEventFeedData(store.model, store.applyCrossfilter(viewId), {
    at,
    type,
    severity,
    message,
  });

  return (
    <DsEventFeedPanel
      data={data as DsEventFeedPanelEvent[]}
      label={label}
      maxHeight={maxHeight}
      height={height}
      className={className}
    />
  );
}
