// packages/dataviz-svelte/src/lib/GeoHexbinMap.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type GeoHexbinMapProps = {
    store: DashboardStore;
    viewId: string;
    latitude: string;
    longitude: string;
    value?: string;
    cellSize?: number;
    width?: number;
    height?: number;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { GeoChart as DsGeoChart } from '@sentropic/design-system-svelte';
  import { useDashboard } from '../adapter.js';
  import { hexbinLayer, mapClass } from './geoMapLayers.js';

  let {
    store,
    viewId,
    latitude,
    longitude,
    value,
    cellSize,
    width = 520,
    height = 320,
    label,
    class: className,
  }: GeoHexbinMapProps = $props();

  const dash = $derived(useDashboard(store));
  const layer = $derived.by(() => {
    void $dash;
    return hexbinLayer(store, viewId, { latitude, longitude, value, cellSize, labelText: label });
  });
  const layers = $derived([layer]);
  const classes = $derived(mapClass('st-geoHexbinMap', className));
</script>

<DsGeoChart {layers} {width} {height} {label} class={classes} />

// packages/dataviz-react/src/lib/GeoHexbinMap.tsx
import type { DashboardStore } from '@sentropic/dataviz-core';
import { GeoChart } from '@sentropic/design-system-react';
import { useDashboard } from '../adapter.js';
import { hexbinLayer, mapClass } from './geoMapLayers.js';

export type GeoHexbinMapProps = {
  store: DashboardStore;
  viewId: string;
  latitude: string;
  longitude: string;
  value?: string;
  cellSize?: number;
  width?: number;
  height?: number;
  label: string;
  className?: string;
};

export function GeoHexbinMap({
  store,
  viewId,
  latitude,
  longitude,
  value,
  cellSize,
  width = 520,
  height = 320,
  label,
  className,
}: GeoHexbinMapProps) {
  const state = useDashboard(store);
  void state;
  const layer = hexbinLayer(store, viewId, { latitude, longitude, value, cellSize, labelText: label });

  return (
    <GeoChart
      layers={[layer]}
      width={width}
      height={height}
      label={label}
      className={mapClass('st-geoHexbinMap', className)}
    />
  );
}
