// packages/dataviz-svelte/src/lib/KpiCardGroup.svelte
<script lang="ts" module>
  import type { DashboardStore, KpiCardConfig, Row } from '@sentropic/dataviz-core';
  import type {
    KpiCardDeltaFormat,
    KpiCardFormat,
    KpiCardSize,
    KpiCardTone,
  } from '@sentropic/design-system-svelte';

  export type KpiCardGroupProps = {
    store: DashboardStore;
    viewId?: string;
    configs: KpiCardConfig[];
    comparisonData?: readonly Row[];
    format?: KpiCardFormat;
    deltaFormat?: KpiCardDeltaFormat;
    size?: KpiCardSize;
    tone?: KpiCardTone;
    class?: string;
  };
</script>

<script lang="ts">
  import { KpiCard } from '@sentropic/design-system-svelte';
  import { buildKpiCards } from '@sentropic/dataviz-core';
  import { useDashboard } from '../adapter.js';

  let {
    store,
    viewId,
    configs,
    comparisonData,
    format,
    deltaFormat = 'percent',
    size,
    tone,
    class: className,
  }: KpiCardGroupProps = $props();

  const dash = $derived(useDashboard(store));
  const cards = $derived.by(() => {
    void $dash;
    return buildKpiCards(store.model, store.applyCrossfilter(viewId), configs, { comparisonData });
  });

  const finite = (value: number | undefined): number | undefined =>
    value === undefined || !Number.isFinite(value) ? undefined : value;
</script>

<div class={className}>
  {#each cards as card (card.id)}
    <KpiCard
      value={card.value}
      label={card.label}
      delta={finite(deltaFormat === 'absolute' ? card.delta : card.deltaPercent)}
      {deltaFormat}
      {format}
      {size}
      {tone}
      sparkline={card.sparkline?.map((point) => point.value)}
    />
  {/each}
</div>

// packages/dataviz-react/src/lib/KpiCardGroup.tsx
import {
  KpiCard,
  type KpiCardDeltaFormat,
  type KpiCardFormat,
  type KpiCardSize,
  type KpiCardTone,
} from '@sentropic/design-system-react';
import {
  buildKpiCards,
  type DashboardStore,
  type KpiCardConfig,
  type Row,
} from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type KpiCardGroupProps = {
  store: DashboardStore;
  viewId?: string;
  configs: KpiCardConfig[];
  comparisonData?: readonly Row[];
  format?: KpiCardFormat;
  deltaFormat?: KpiCardDeltaFormat;
  size?: KpiCardSize;
  tone?: KpiCardTone;
  className?: string;
};

function finite(value: number | undefined): number | undefined {
  return value === undefined || !Number.isFinite(value) ? undefined : value;
}

export function KpiCardGroup({
  store,
  viewId,
  configs,
  comparisonData,
  format,
  deltaFormat = 'percent',
  size,
  tone,
  className,
}: KpiCardGroupProps) {
  useDashboard(store);
  const cards = buildKpiCards(store.model, store.applyCrossfilter(viewId), configs, {
    comparisonData,
  });

  return (
    <div className={className}>
      {cards.map((card) => (
        <KpiCard
          key={card.id}
          value={card.value}
          label={card.label}
          delta={finite(deltaFormat === 'absolute' ? card.delta : card.deltaPercent)}
          deltaFormat={deltaFormat}
          format={format}
          size={size}
          tone={tone}
          sparkline={card.sparkline?.map((point) => point.value)}
        />
      ))}
    </div>
  );
}
