// packages/dataviz-svelte/src/lib/PercentileBandChart.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type PercentileBandChartProps = {
    store: DashboardStore;
    viewId: string;
    value: string;
    lower: number;
    upper: number;
    width?: number;
    height?: number;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { buildPercentileBandModel } from '@sentropic/dataviz-core';
  import { LineChart as DsLineChart, type LineChartDatum } from '@sentropic/design-system-svelte';
  import { useDashboard } from '../adapter.js';

  let {
    store,
    viewId,
    value,
    lower,
    upper,
    width = 360,
    height = 96,
    label,
    class: className,
  }: PercentileBandChartProps = $props();

  const dash = $derived(useDashboard(store));
  const model = $derived.by(() => {
    void $dash;
    return buildPercentileBandModel(store.model, store.applyCrossfilter(viewId), { value, lower, upper });
  });
  const data = $derived.by(
    (): LineChartDatum[] => [
      { x: `${Math.round(lower * 100)}%`, y: model.lowerValue },
      { x: 'median', y: model.median },
      { x: `${Math.round(upper * 100)}%`, y: model.upperValue },
    ],
  );
  const bands = $derived([{ from: model.lowerValue, to: model.upperValue, label: 'Percentiles', tone: 'success' as const }]);
  const referenceLines = $derived([{ value: model.median, label: 'Median', tone: 'success' as const }]);
  const classes = $derived(['st-percentileBandChart', className].filter(Boolean).join(' '));
</script>

<DsLineChart {data} {width} {height} {label} {bands} {referenceLines} class={classes} />

// packages/dataviz-react/src/lib/PercentileBandChart.tsx
import { buildPercentileBandModel, type DashboardStore } from '@sentropic/dataviz-core';
import { LineChart, type LineChartDatum } from '@sentropic/design-system-react';
import { useDashboard } from '../adapter.js';

export type PercentileBandChartProps = {
  store: DashboardStore;
  viewId: string;
  value: string;
  lower: number;
  upper: number;
  width?: number;
  height?: number;
  label: string;
  className?: string;
};

export function PercentileBandChart({
  store,
  viewId,
  value,
  lower,
  upper,
  width = 360,
  height = 96,
  label,
  className,
}: PercentileBandChartProps) {
  const state = useDashboard(store);
  void state;
  const model = buildPercentileBandModel(store.model, store.applyCrossfilter(viewId), { value, lower, upper });
  const data: LineChartDatum[] = [
    { x: `${Math.round(lower * 100)}%`, y: model.lowerValue },
    { x: 'median', y: model.median },
    { x: `${Math.round(upper * 100)}%`, y: model.upperValue },
  ];

  return (
    <LineChart
      data={data}
      width={width}
      height={height}
      label={label}
      bands={[{ from: model.lowerValue, to: model.upperValue, label: 'Percentiles', tone: 'success' }]}
      referenceLines={[{ value: model.median, label: 'Median', tone: 'success' }]}
      className={['st-percentileBandChart', className].filter(Boolean).join(' ') || undefined}
    />
  );
}
