// packages/dataviz-angular/src/lib/RibbonChart.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Input as NgInput, inject } from '@angular/core';
import type { OnChanges, OnDestroy, OnInit } from '@angular/core';
import { RibbonChart as DsRibbonChart, type RibbonChartDatum } from '@sentropic/design-system-angular';
import { buildRibbonData, type DashboardStore } from '@sentropic/dataviz-core';
import { toSignalStore, type AngularSignalStore } from '../adapter.js';

export type RibbonChartProps = {
  store: DashboardStore;
  viewId: string;
  category: string;
  period: string;
  value: string;
  width?: number;
  height?: number;
  size?: number;
  label?: string;
  class?: string;
};

/**
 * State wiring for a DS Angular RibbonChart.
 * Generated from tools/dataviz-angular-port/descriptors.json — see that
 * directory's README before editing this file by hand.
 */
@Component({
  selector: 'st-dataviz-ribbon-chart',
  standalone: true,
  imports: [DsRibbonChart],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <st-ribbon-chart
      [data]="data"
      [label]="label"
      [width]="width"
      [height]="height"
      [size]="size"
      [class]="classInput"
    ></st-ribbon-chart>
  `,
})
export class RibbonChart implements OnInit, OnChanges, OnDestroy {
  static readonly stComponentName = 'RibbonChart';

  private readonly changeDetector = inject(ChangeDetectorRef);
  private signals?: AngularSignalStore;
  private unsubscribe: () => void = () => {};

  @NgInput({ required: true }) set store(value: DashboardStore) {
    if (this.signals) this.signals.replace(value);
    else this.signals = toSignalStore(value);
    this.unsubscribe();
    this.unsubscribe = value.subscribe(() => {
      this.recompute();
      this.changeDetector.markForCheck();
    });
  }

  get store(): DashboardStore {
    if (!this.signals) {
      throw new Error('RibbonChart: store is required.');
    }
    return this.signals.store;
  }

  @NgInput({ required: true }) viewId!: string;
  @NgInput({ required: true }) category!: string;
  @NgInput({ required: true }) period!: string;
  @NgInput({ required: true }) value!: string;
  @NgInput() width?: number;
  @NgInput() height?: number;
  @NgInput() size?: number;
  @NgInput() label?: string;
  @NgInput('class') classInput?: string;

  /** Recomputed by `recompute()`; never derived in a template getter. */
  data: RibbonChartDatum[] = [];

  ngOnInit(): void {
    this.recompute();
  }

  ngOnChanges(): void {
    this.recompute();
  }

  ngOnDestroy(): void {
    this.unsubscribe();
    this.signals?.destroy();
  }

  private recompute(): void {
    if (!this.signals) return;
    void this.signals.state();
    this.data = buildRibbonData(
      this.signals.store.model,
      this.signals.store.applyCrossfilter(this.viewId),
      {
        category: this.category,
        period: this.period,
        value: this.value,
      },
    );
  }
}

// packages/dataviz-react/src/lib/RibbonChart.tsx
import {
  RibbonChart as DsRibbonChart,
  type RibbonChartDatum,
} from '@sentropic/design-system-react';
import type { DashboardStore } from '@sentropic/dataviz-core';
import { buildRibbonData } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type RibbonChartProps = {
  store: DashboardStore;
  viewId: string;
  /** Field id whose value becomes the category (string-coerced). */
  category: string;
  /** Field id whose value becomes the period (string | number preserved). */
  period: string;
  /** Field id whose numeric value becomes the ribbon height/value. */
  value: string;
  width?: number;
  height?: number;
  size?: number;
  /** Accessible label for the chart (aria-label). */
  label?: string;
  className?: string;
};

export function RibbonChart({
  store,
  viewId,
  category,
  period,
  value,
  width,
  height,
  size,
  label,
  className,
}: RibbonChartProps) {
  const state = useDashboard(store);
  void state;

  const data = buildRibbonData(store.model, store.applyCrossfilter(viewId), {
    category,
    period,
    value,
  });

  return (
    <DsRibbonChart
      data={data as RibbonChartDatum[]}
      label={label}
      width={width}
      height={height}
      size={size}
      className={className}
    />
  );
}
