// packages/components-angular/src/Inline.ts
import { Component, Input as NgInput } from "@angular/core";

import { classNames } from "./classNames.js";

import { Flex } from "./Flex.js";

import type { FlexAlign, FlexJustify } from "./Flex.js";

export type InlineProps = {
  /** Spacing scale step (0..12) mapped to `--st-spacing-*`. */
  gap?: number;
  align?: FlexAlign;
  justify?: FlexJustify;
  wrap?: boolean;
  as?: string;
  class?: string;
};

@Component({
  selector: "st-inline",
  standalone: true,
  template: `
    <div [attr.data-st-component]="componentName" [class]="hostClass">
      <ng-content></ng-content>
    </div>
  `,
})
export class Inline {
  static readonly stComponentName = "Inline";
  readonly componentName = "Inline";
  @NgInput() gap?: number;
  @NgInput() align?: FlexAlign;
  @NgInput() justify?: FlexJustify;
  @NgInput() wrap?: boolean;
  @NgInput() as?: string;
  @NgInput("class") classInput?: string;

  get hostClass(): string {
    return ["st-inline", this.classInput].filter(Boolean).join(" ");
  }
}

// packages/components-svelte/src/lib/Inline.svelte
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { FlexAlign, FlexJustify } from "./Flex.svelte";

  export type InlineProps = Omit<HTMLAttributes<HTMLElement>, "class"> & {
    /** Spacing scale step (0..12) mapped to `--st-spacing-*`. */
    gap?: number;
    align?: FlexAlign;
    justify?: FlexJustify;
    wrap?: boolean;
    as?: string;
    class?: string;
    children?: Snippet;
  };
</script>

<script lang="ts">
  import Flex from "./Flex.svelte";

  let {
    gap,
    align,
    justify,
    wrap = true,
    as = "div",
    class: className,
    children,
    ...rest
  }: InlineProps = $props();

  const classes = $derived(["st-inline", className].filter(Boolean).join(" "));
</script>

<Flex {...rest} {as} {gap} {align} {justify} {wrap} direction="row" class={classes}>
  {@render children?.()}
</Flex>
