// packages/components-angular/src/SkeletonText.ts
import { Component, Input as NgInput } from "@angular/core";

import { classNames } from "./classNames.js";

export type SkeletonTextProps = {
  lines?: number;
  width?: string;
  heading?: boolean;
  paragraph?: boolean;
  locale?: string;
  loadingLabel?: string;
  class?: string;
};

@Component({
  selector: "st-skeleton-text",
  standalone: true,
  template: `
    <div
      [attr.data-st-component]="componentName"
      [class]="hostClass"
      role="status"
      [attr.aria-label]="resolvedLoadingLabel"
      aria-busy="true"
    >
      @for (i of linesArray; track $index) {
        <span [class]="lineClass" [style.width]="lineWidth($index, linesArray.length)"></span>
      }
    </div>
  `,
})
export class SkeletonText {
  static readonly stComponentName = "SkeletonText";
  readonly componentName = "SkeletonText";
  @NgInput() lines?: number;
  @NgInput() width?: string;
  @NgInput() heading?: boolean;
  @NgInput() paragraph?: boolean;
  @NgInput() locale?: string;
  @NgInput() loadingLabel?: string;
  @NgInput("class") classInput?: string;

  get isFr(): boolean {
    return (this.locale ?? "fr-FR").toLowerCase().startsWith("fr");
  }

  get resolvedLoadingLabel(): string {
    if (this.loadingLabel != null) return this.loadingLabel;
    return this.isFr ? "Chargement…" : "Loading…";
  }

  get lineCount(): number {
    const lines = this.lines ?? 1;
    return this.paragraph ? Math.max(lines, 3) : lines;
  }

  get linesArray(): number[] {
    return Array.from({ length: Math.max(0, this.lineCount) }, (_, i) => i);
  }

  get lineClass(): string {
    return classNames("st-skeleton__line", this.heading && "st-skeleton__line--heading");
  }

  lineWidth(index: number, total: number): string | undefined {
    if (this.width && index === 0) return this.width;
    if (this.paragraph && index === total - 1) return "60%";
    return undefined;
  }

  get hostClass(): string {
    return classNames("st-skeleton", this.classInput);
  }
}

// packages/components-svelte/src/lib/SkeletonText.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";

  type SkeletonTextProps = Omit<HTMLAttributes<HTMLDivElement>, "class"> & {
    lines?: number;
    width?: string;
    heading?: boolean;
    paragraph?: boolean;
    locale?: string;
    loadingLabel?: string;
    class?: string;
  };

  let {
    lines = 1,
    width,
    heading = false,
    paragraph = false,
    locale = "fr-FR",
    loadingLabel,
    class: className,
    ...rest
  }: SkeletonTextProps = $props();

  const isFr = $derived(locale.toLowerCase().startsWith("fr"));
  const resolvedLoadingLabel = $derived(loadingLabel ?? (isFr ? "Chargement…" : "Loading…"));

  const wrapperClasses = () => ["st-skeleton", className].filter(Boolean).join(" ");
  const lineClasses = () =>
    ["st-skeleton__line", heading ? "st-skeleton__line--heading" : null].filter(Boolean).join(" ");
  const lineCount = () => (paragraph ? Math.max(lines, 3) : lines);

  function lineWidth(index: number, total: number): string | undefined {
    if (width && index === 0) return width;
    if (paragraph && index === total - 1) return "60%";
    return undefined;
  }
</script>

<div {...rest} class={wrapperClasses()} role="status" aria-label={resolvedLoadingLabel} aria-busy="true">
  {#each Array.from({ length: lineCount() }) as _, i (i)}
    <span class={lineClasses()} style={lineWidth(i, lineCount()) ? `width:${lineWidth(i, lineCount())}` : undefined}></span>
  {/each}
</div>

<style>
  .st-skeleton {
    display: grid;
    gap: 0.5rem;
    width: 100%;
  }

  .st-skeleton__line {
    background: linear-gradient(
      90deg,
      var(--st-semantic-surface-subtle, #eaeef2),
      var(--st-semantic-border-subtle, #d8dee4),
      var(--st-semantic-surface-subtle, #eaeef2)
    );
    background-size: 200% 100%;
    border-radius: 0.25rem;
    display: block;
    height: 0.875rem;
    width: 100%;
    animation: st-skeleton-shimmer 1.4s ease-in-out infinite;
  }

  .st-skeleton__line--heading {
    height: 1.25rem;
  }

  @keyframes st-skeleton-shimmer {
    0% {
      background-position: 200% 0;
    }
    100% {
      background-position: -200% 0;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .st-skeleton__line {
      animation: none;
    }
  }
</style>
